name: tvcare_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  jwt_decoder: ^2.0.1
  flutter_dotenv: ^6.0.0
  shared_preferences: ^2.5.4
  http: ^1.6.0
  intl: ^0.18.1
  excel: ^4.0.2
  path_provider: ^2.1.1
  file_saver: ^0.2.13
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.2.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^10.1.0
  geocoding: ^3.0.0
  dio: ^5.4.0
  url_launcher: ^6.2.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - .env
  uses-material-design: true
